### PR TITLE
Added subdomain support

### PR DESCRIPTION
**Pull request by httpdop**
Added support for subdomains.

### CODE REVIEW

**Comment by dschoeffm** [comment]
That you for the MR :)

There is however an issue with your approach:
You are assuming, that `xyz.example.com` and `abc.def.example.com` are in different zones. However, it is totally legitimate to have both in the same zone. Nothing forbids that. I'm not sure, if that is the case for anyone currently using this script, in case it is, I don't want to break their setup.

I do agree with you, that this is not (or should not be) the usual case.

One way out of that problem would be to loop over the possible domains. You would probably want to start with the longest possible one and make your way to the shorter domains (one dot at a time), and use the first existing domain.

**Comment by dschoeffm** [comment]
Also the history is a bit messy. You made 4 commits, when (in my opinion) it should be one.
You may want to take a look at squashing those commits together. `git rebase -i <...>` is a great tool for that.

This seems like a good tutorial for that: https://www.internalpointers.com/post/squash-commits-into-one-git

**Comment by httpdop** [comment]
Thanks for your response to my PR.

I am not shure if I understand your feedback right, but my approch is to add the txt records to one zonefile e.g.

**certbot**
`certbot certonly --manual --preferred-challenges=dns --manual-auth-hook /usr/local/bin/certbot-hetzner-auth.sh --manual-cleanup-hook /usr/local/bin/certbot-hetzner-cleanup.sh -d example.com -d *.xyz.example -d *.abc.def.example.com`

**certbot output**
Obtaining a new certificate
Performing the following challenges:
dns-01 challenge for abc.def.example.com
dns-01 challenge for xyz.example

The script "certbot-hetzner-auth.sh" within the PR creates the following txt records in the zone "<domain name>.<tld>" here example.com 

**zone file "example.com"**
_acme-challenge.abc.def.example.com.	300	IN	TXT	<Let's Encrypt ID1>
_acme-challenge.xyz.example.com.	        300	IN	TXT	<Let's Encrypt ID2>

The cleanup script removes only the lines added before.

The variable "search_name" holds in any case "<domain name>.<tld>" 
`search_name=$( echo $CERTBOT_DOMAIN | rev | cut -d'.' -f 1,2 | rev)`

**That means for the example above:**

- The first dns-01 challenge "abc.def.example.com" leads to
-- CERTBOT_DOMAIN = abc.def.example.com
-- search_name = example.com

- The second dns-01 challenge "xyz.example.com" leads to
-- CERTBOT_DOMAIN = xyz.example.com
-- search_name = example.com

At the moment your original script searches direct with the "CERTBOT_DOMAIN" variable to find the zone file. That means your script searches in the above case 
for  "abc.def.example.com" and "xyz.example.com" and if available it will add one txt record to "abc.def.example.com" and one txt record to "xyz.example.com". But if only one zone file exists it will stop working. Or am I wrong? Is that your default use case?


> One way out of that problem would be to loop over the possible domains. You would probably want to start with the longest possible one and make your way to the shorter domains (one dot at a time), and use the first existing domain.

That's a sollution to support both use caes that's right.

**Comment by httpdop** [comment]
> Also the history is a bit messy. You made 4 commits, when (in my opinion) it should be one.
>You may want to take a look at squashing those commits together. git rebase -i <...> is a great tool for that.

>This seems like a good tutorial for that: >https://www.internalpointers.com/post/squash-commits-into-one-git

I will check the side thanks for the hint.

**Comment by httpdop** [comment]
I checked the website you mentioned above, but I cant rebase it.

**Comment by httpdop** [comment]
I can create a new branch from your upstream master and create a new pull request wiht only one commit. Please check first my second pull request.

**Comment by dschoeffm** [comment]
The discussion pretty much moved to #5

**Comment by httpdop** [comment]
Hi Dominik,

I added a clean pull request https://github.com/dschoeffm/hetzner-dns-certbot/pull/6

**Comment by dschoeffm** [comment]
See #6

**Pull request closed without merging**
